### ISSUE TITLE
Nether/End Metals ore have no recipes

### ISSUE THREAD

**Issue by SpartanSamuel** [Siriuo/Wirenut-Modpack#10]
Only the first seven ores listed in Nether Metals and End Metals actually have recipes to do stuff with. Even mining them without silk touch, they only drop themselves. They can't be put into any kind of machine to ground or liquefy. The only thing I can do with them is create a facade from AE2 based on the ore.

**Comment by iDarper** [comment]
I'll have to look into this later tonight.  I pretty sure they can be smelted

**Comment by Siriuo** [comment]
Likely resolved with recent updates.

**Comment by SpartanSamuel** [comment]
Confirmed fixed in update 3.4. They can be smelted into vanilla Iron Ore.
