### ISSUE TITLE
Ore dict between Yellorite and Uranium broken

### ISSUE THREAD

**Issue by SpartanSamuel** [Siriuo/Wirenut-Modpack#11]
First, the Yellorite plant from Mystical Agriculture only yields Uranium ingots. Mainly though some recipes that require Yellorite, but show Uranium because of the ore dict reference, will show the crafting recipe as working in the grid but won't actually let you take the crafting result unless you use Yellorite instead.

**Comment by iDarper** [comment]
Uranium and yellorite can be used interchangeably.  Both for recipes and for fuel in big reactors

**Comment by SpartanSamuel** [comment]
I'll upload video after dinner, but though Uranium _shows_ as a valid recipe it won't allow you to take the result from the crafting grid unless Yellorite is used. It's a false positive.

**Comment by SpartanSamuel** [comment]
The Mystical Agriculture works fine, but the crafting issue persists through update 3.4.

**Comment by iDarper** [comment]
It's a simple config change.  Chances are,  the civic was changed by the mod dev between versions
