### ISSUE TITLE
Uncrafting Grinder ignores blacklist

### ISSUE THREAD

**Issue by SpartanSamuel** [Siriuo/Wirenut-Modpack#12]
Even though Cyclic's Uncrafting Grinder has Progressive Automation's Wither Diamonds blacklisted properly, I'm still able to uncraft them and receive wither stars and diamonds anyways. The '?' in the Uncrafter's GUI even states it's on the blacklist.

I recommend simply putting vanilla wither stars on the output blacklist, as there's actually two separate blacklists in the config (input and output).

**Comment by SpartanSamuel** [comment]
This issue persists through update 3.4.

**Comment by iDarper** [comment]
I'll look into adding this later after work

**Comment by Siriuo** [comment]
Confirmed as resolved in 3.4 after config changes server side.
