### ISSUE TITLE
Recipes that asks for filled buckets or bottles, "eats" those buckets or bottles

### ISSUE THREAD

**Issue by amras471** [Siriuo/Wirenut-Modpack#3]
So far, while trying to make Fresh Water (Harvestcraft item), Rice slimeball (Actually Additions) or any recipe that asks for a bucket of water, or a bottle of water (or any liquid), the recipe eliminates the bucket/bottle. This was not happening on past versions of the Wirenut modpack.

**Comment by iDarper** [comment]
Not sure what is causing this issue. I'll get Siriuo to look into it.
