### ISSUE TITLE
Metal Nuggets are converted to Agricraft ones. Can't get back the ingot on a CraftTable

### ISSUE THREAD

**Issue by amras471** [Siriuo/Wirenut-Modpack#5]
As it says, when I made copper nuggets and wanted to convert them back to ingots, the Craft Table / Craft Station doesn't give me the ingot in either Vanilla or Metal mod (like Base Metals)

**Comment by iDarper** [comment]
Did you try the little arrow to the right side?  If there's 2 our more items that use the same recipe,  you can switch between them

**Comment by iDarper** [comment]
removed agricraft until it's more stable.
