### ISSUE TITLE
Thermal Foundation mods: Reinforced Bow being replaced (material)

### ISSUE THREAD

**Issue by amras471** [Siriuo/Wirenut-Modpack#6]
Trying to make a Shiny (Platinum) Reinforced Bow gives instead a Copper Reinforced Bow. It is insta-replaced. No idea if this has to do with the Thermal materials like Electrum and others but maybe it is not exclusive of Platinum.

**Comment by Siriuo** [comment]
This is unlikely to be resolved any time soon due to TF not being officially released. Will keep an eye out for any fixes.
