### ISSUE TITLE
Redundant Ore Generation between Mods

### ISSUE THREAD

**Issue by SpartanSamuel** [Siriuo/Wirenut-Modpack#7]
So I went through and checked all mods that affect World Gen and there's legit 6x different mods that add a unique variant of Copper that each doesn't stack with the others in my inventory. Seems like a waste of space. I understand that UniDict and OreDictionaryConverter are meant to fix that when the ore is processed, but even then going into a ravine and seeing 50 different kinds of ores seems great at first, but when you realize that 1/3 of it is just all sorts of different Tins your excitement drops.

Below is a list of all the ores that repeat themselves via multiple mods' world gen configs:

- Aluminum: Immersive Engineering, Thermal Foundation
- Copper: Base Metals, Forestry, Immersive Engineering, Industrial Craft 2, Magneticraft, Mekanism, NeoTech, Railcraft, Thermal Foundation
- Lead: Base Metals, Immersive Engineering, Industrial Craft 2, Magneticraft, NeoTech, Railcraft, Thermal Foundation
- Nickel: Base Metals, Immersive Engineering, Thermal Foundation
- Platinum: Base Metals, Thermal Foundation
- Silver: Base Metals, Immersive Engineering, NeoTech, Railcraft, Thermal Foundation
- Tin: Base Metals, Forestry, Industrial Craft 2, Mekanism, NeoTech, Railcraft, Thermal Foundation
- Uranium: Immersive Engineering, Industrial Craft 2

In general I'd prefer if we kept to a single source per ore (of course not including mods like Nether Metals/End Metals/Nether Core because they add vanilla materials to multiple dimensions). I'm not too familiar with Magneticraft, Mekanism, NeoTech, and Thermal Foundation's configs but I know the rest are configurable to blacklist specific ores from spawning per mod.

**Comment by SpartanSamuel** [comment]
Actually, Nether Core and Nether Metals duplicate the production of Coal, Diamond, Emerald, Gold, Iron, Lapis Lazuli, and Redstone ore. This obviously occurs specifically in the Nether, but still.

**Comment by iDarper** [comment]
One of our other players,  (ArbitraryAlex)  went thru the configs,  and changed them for  us.  But the server overrided them fire some reason.  We can revisit this issue later,  since all of the overworld is already regenerated and new configs would not have any affect at  this point closing For now.

**Comment by iDarper** [comment]
Pregenerated, not regenerated.  (Stupid autocorrect)

**Comment by SpartanSamuel** [comment]
Are there backup copies of the configs before they were overridden? Have any world gen mods been added since the configs were set?
